/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../api.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/http';
import * as i4 from '../api/pet.service';
import * as i5 from '@angular/common/http';
import * as i6 from '../variables';
import * as i7 from '../configuration';
import * as i8 from '../api/store.service';
import * as i9 from '../api/user.service';
export const ApiModuleNgFactory:i0.NgModuleFactory<i1.ApiModule> = i0.ɵcmf(i1.ApiModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BrowserXhr,
          i3.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i3.ResponseOptions,i3.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i3.XSRFStrategy,i3.ɵb,([] as any[])),i0.ɵmpd(4608,
          i3.XHRBackend,i3.XHRBackend,[i3.BrowserXhr,i3.ResponseOptions,i3.XSRFStrategy]),
          i0.ɵmpd(4608,i3.RequestOptions,i3.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i3.Http,i3.ɵc,[i3.XHRBackend,i3.RequestOptions]),i0.ɵmpd(4608,i4.PetService,
              i4.PetService,[i5.HttpClient,[2,i6.BASE_PATH],[2,i7.Configuration]]),
          i0.ɵmpd(4608,i8.StoreService,i8.StoreService,[i5.HttpClient,[2,i6.BASE_PATH],
              [2,i7.Configuration]]),i0.ɵmpd(4608,i9.UserService,i9.UserService,[i5.HttpClient,
              [2,i6.BASE_PATH],[2,i7.Configuration]]),i0.ɵmpd(512,i2.CommonModule,
              i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.HttpModule,i3.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i1.ApiModule,i1.ApiModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NlYmFzdGlhbi9Eb2N1bWVudHMvRGV2ZWxvcG1lbnQvc3dhZ2dlci1jb2RlZ2VuL3NhbXBsZXMvY2xpZW50L3BldHN0b3JlL3R5cGVzY3JpcHQtYW5ndWxhci12NC4zL25wbS13aXRoLWFvdC9hcGkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NlYmFzdGlhbi9Eb2N1bWVudHMvRGV2ZWxvcG1lbnQvc3dhZ2dlci1jb2RlZ2VuL3NhbXBsZXMvY2xpZW50L3BldHN0b3JlL3R5cGVzY3JpcHQtYW5ndWxhci12NC4zL25wbS13aXRoLWFvdC9hcGkubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
